Warn

diff --git a/.github/workflows/tps-verify.yml b/.github/workflows/tps-verify.yml
--- a/.github/workflows/tps-verify.yml
+++ b/.github/workflows/tps-verify.yml
@@ -45,7 +45,13 @@ jobs:
           set +e
 
           tps verify | tee verify-result.txt
-          grep ERROR: verify-result.txt >/dev/null
+
+          grep "WARNING:" verify-result.txt >/dev/null
           if [ $? -eq 0 ]; then
-            exit 1
+            echo "::warning ::WARNING found"
+          fi
+
+          grep "ERROR:" verify-result.txt >/dev/null
+          if [ $? -eq 0 ]; then
+            echo "::error ::ERROR found"
           fi
